version: '2.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: gophermart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ../../go-dev-final-db/:/var/lib/postgresql/data/

  app:
    build:
      context: ../
      dockerfile: build/app.Dockerfile
    image: gophermart
    entrypoint: /docker-app
    depends_on:
      - db
      - accural
    environment:
      DATABASE_DSN: postgres://postgres:password@db/gophermart
      SERVER_ADDRESS: 0.0.0.0:8080
      BASE_URL: http://127.0.0.1:8080/
    ports:
      - "127.0.0.1:8080:8080"

  accural:
    build:
      context: ../
      dockerfile: build/accural.Dockerfile
    image: gophermart-accural
